atm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home, LogoutView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),

    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    url(r'^card/', include('cards.urls'))
]

cards/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    CardDetailView,
    CardCheckoutView,
    CardNumberValidationView,
    CardPasswordValidationView,
    CardOperationsView,
    CardWithdrawalView,
)

app_name = 'cards'

urlpatterns = [
    url(r'^num/$', CardNumberValidationView.as_view(), name='num_validator'),
    url(r'^pass/$', CardPasswordValidationView.as_view(), name='pass_validator'),
    url(r'^menu/$', CardOperationsView.as_view(), name='menu'),
    url(r'^detail/$', CardDetailView.as_view(), name='detail'),
    url(r'^withdrawal/$', CardWithdrawalView.as_view(), name='withdrawal'),
    url(r'^checkout/$', CardCheckoutView.as_view(), name='checkout'),

]

cards/models.py
import hashlib

from django.db import models
from django.db.models.signals import post_save, pre_save

# Create your models here.
class CardQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(locked=False)


class CardManager(models.Manager):
    def get_queryset(self):
        return CardQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()


class Card(models.Model):
    number = models.TextField(max_length=16, unique=True)
    password = models.TextField(max_length=256)
    locked = models.BooleanField(default=False)
    balance = models.IntegerField(default=0)

    objects = CardManager()

    def __str__(self):
        return self.number


def card_item_post_save_receiver(sender, instance, created, *args, **kwargs):
    if created:
        password = instance.password
        password = hashlib.md5(password.encode())
        instance.password = password.hexdigest()
        instance.save()

post_save.connect(card_item_post_save_receiver, sender=Card)


TRANSACTION_TYPE_CHOICES = (
    ('balance', 'Balance'),
    ('withdrawal', 'Withdrawal'),
)

class Transaction(models.Model):
    card        = models.ForeignKey(Card, on_delete=models.CASCADE)
    type        = models.CharField(max_length=120, choices=TRANSACTION_TYPE_CHOICES)
    timestamp   = models.DateTimeField(auto_now_add=True, auto_now=False)
    cash_value  = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.card}:{self.type}:{self.timestamp}'


def transaction_pre_save_receiver(sender, instance, *args, **kwargs):
    if instance.type == 'balance':
        instance.cash_value = instance.card.balance
    if instance.type == 'withdrawal':
        instance.card.balance -= instance.cash_value
        instance.card.save()

pre_save.connect(transaction_pre_save_receiver, sender=Transaction)

cards/views.py
from django.contrib import messages
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, reverse, get_object_or_404
from django.views.generic.base import View
from django.views.generic.detail import SingleObjectMixin

from .models import Card, Transaction
from .mixins import CardNumberMixin, CardLoginMixin

# Create your views here.
class CardNumberValidationView(SingleObjectMixin, View):
    model = Card

    def get_object(self):
        # 300seconds = 5minutes | 0 = session cookies will expire when Web browser is closed
        self.request.session.set_expiry(0)
        number = self.request.POST.get('card')
        try:
            card = Card.objects.all().filter(number=number).first()
            return card
        except:
            return None

    def get(self, request):
        return HttpResponseRedirect('/')

    def post(self, request, *args, **kwargs):
        card = self.get_object()
        if not card:
            #messages.error(self.request, 'Incorrect card number or your card is probably blocked!')
            #return HttpResponseRedirect('/')
            message = 'Incorrect card number or your card is probably blocked!'
            return render(request, 'cards/card-error.html', {'message': message})
        request.session['number'] = card.number

        # initialize pin counter for each card
        if not request.session.get(card.number):
            request.session[card.number] = 0
        return HttpResponseRedirect(reverse('cards:pass_validator'))


class CardPasswordValidationView(CardNumberMixin, SingleObjectMixin, View):
    model = Card
    PIN_LIMIT = 3

    def lock_card(self):
        number = self.request.session.get('number')
        card = Card.objects.all().filter(number=number).first()
        card.locked = True
        card.save()
        del self.request.session['number']
        del self.request.session[number]

    def get_object(self):
        number = self.request.session.get('number')
        password = self.request.POST.get('pass')
        try:
            card = Card.objects.all().filter(number=number, password=password).first()
            return card
        except:
            return None

    def get(self, request):
        return render(request, 'cards/card-password.html', {})

    def post(self, request):
        card_number = request.session.get('number')
        card = self.get_object()
        if card:
            request.session['password'] = True
            request.session[card_number] = 0
            return HttpResponseRedirect(reverse('cards:menu'))
        pin_invalid_counter = request.session.get(card_number)
        pin_invalid_counter += 1
        request.session[card_number] = pin_invalid_counter
        message = 'Wrong password!'
        if pin_invalid_counter > self.PIN_LIMIT:
            self.lock_card()
            message = 'Your card is blocked!'
        return render(request, 'cards/card-error.html', {'message':message})


class CardOperationsView(CardLoginMixin, SingleObjectMixin, View):
    model = Card
    template_name = 'cards/card-operations.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class CardDetailView(CardLoginMixin, SingleObjectMixin, View):
    model = Card
    template_name = 'cards/card-detail.html'

    def get_object(self, queryset=None):
        card_number = self.request.session.get('number')
        object = get_object_or_404(Card, number=card_number)
        return object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get(self, request):
        self.object = self.get_object()
        context = self.get_context_data()
        transaction = Transaction()
        transaction.card = self.object
        transaction.type = 'balance'
        transaction.save()
        return render(request, self.template_name, context)


class CardWithdrawalView(CardLoginMixin, SingleObjectMixin, View):
    model = Card
    template_name = 'cards/card-withdrawal.html'

    def get_object(self, queryset=None):
        card_number = self.request.session.get('number')
        object = get_object_or_404(Card, number=card_number)
        return object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get(self, request):
        self.object = self.get_object()
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def post(self, request):
        self.object = self.get_object()
        context = self.get_context_data()
        required_cash = int(request.POST.get('cash'))
        current_cash = self.object.balance
        if required_cash < current_cash:
            transaction = Transaction()
            transaction.card = self.object
            transaction.type = 'withdrawal'
            transaction.cash_value = required_cash
            transaction.save()
            return HttpResponseRedirect(reverse('cards:checkout'))

        #messages.error(self.request, 'Not enough money on your card!')
        #return render(request, self.template_name, context)
        message = 'Not enough money on your card!'
        return render(request, 'cards/card-error.html', {'message': message})


class CardCheckoutView(CardLoginMixin, SingleObjectMixin, View):
    template_name = 'cards/card-checkout.html'
    model = Transaction

    def get_object(self, *args, **kwargs):
        card_number = self.request.session.get('number')
        card = get_object_or_404(Card, number=card_number)
        transaction = card.transaction_set.all().order_by('-pk').first()
        return transaction

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get(self, request):
        self.object = self.get_object()
        context = self.get_context_data()
        return render(request, self.template_name, context)

cards/templates/cards/card-checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{block.super}} - Details {% endblock %}

{% block content %}

    <div class="row input-field">
        <h3>Details:</h3>
        <br/>
        <p>Card: {{object.card }}</p>
        <p>Time: {{object.timestamp |date:"D d M Y H:i"}}</p>
        <p>Amount: {{object.cash_value}}</p>
        <p>Balance: {{object.card.balance}} </p>
    </div>

    <div class="row control-row">
        <a href="{% url 'logout' %}"><button class="btn btn-info" value="">Exit</button></a>
        <a href="{% url 'cards:menu' %}"><button class="btn btn-info" value="">Menu</button></a>
        <a href="{% url 'cards:withdrawal' %}"><button disabled class="btn btn-info" disabled value="">Cash</button></a>
    </div>

{% endblock %}

{% block script %}
{% endblock %}

cards/templates/cards/card-detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{block.super}} - Details {% endblock %}

{% block content %}

    <div class="row input-field">
        <h3>Details:</h3>
        <br/>
        <p>Card number: {{object.number}}</p>
        <p>Date: {% now "jS F Y H:i" %}</p>
        <p>Balance: {{object.balance}}</p>
    </div>

    <div class="row control-row">
        <a href="{% url 'logout' %}"><button class="btn btn-info" value="">Exit</button></a>
        <a href="{% url 'cards:menu' %}"><button class="btn btn-info" value="">Menu</button></a>
        <a href="#"><button class="btn btn-info" disabled value="">Cash</button></a>
    </div>

{% endblock %}

{% block script %}
{% endblock %}

cards/templates/cards/card-error.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{block.super}} - Details {% endblock %}

{% block content %}

    <div class="row input-field">
        <h3>Error:</h3>
        <p>{{message}}</p>
    </div>

    <div class="row control-row">
        <a href="{% url 'logout' %}"><button disabled class="btn btn-info" value="">Exit</button></a>
        <a href="{{request.META.HTTP_REFERER}}"><button class="btn btn-info" value="">BACK</button></a>
        <a href="{% url 'cards:withdrawal' %}"><button disabled class="btn btn-info" disabled value="">Cash</button></a>
    </div>

{% endblock %}

{% block script %}
{% endblock %}

cards/templates/cards/card-number.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{block.super}} - Input Card Number{% endblock %}

{% block content %}

    <div class="row input-field">
        <h3>Input card number:</h3>
        <div ><input disabled id="card-num-input" class="align-center" type="text" /></div>
        <br/>
    </div>

    <div class="row control-row">
        <a href="{% url 'logout' %}"><button disabled class="btn btn-info" value="">Exit</button></a>
        <button disabled class="btn" value="">Balance</button>
        <button disabled class="btn" value="">Cash</button>
    </div>
    {% include 'keyboard.html' with action='/card/num/' %}
{% endblock %}

{% block script %}
    <script src="{% static 'js/functions.js' %}"></script>
    <script src="{% static 'js/card_num_validator.js' %}"></script>
{% endblock %}

cards/templates/cards/card-operations.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{block.super}} - Operations {% endblock %}

{% block content %}

    <div class="row input-field">
        <h3>Operations:</h3>
        <br/>
    </div>

    <div class="row control-row">
        <a href="{% url 'logout' %}"><button class="btn btn-info" value="">Exit</button></a>
        <a href="{% url 'cards:detail' %}"><button class="btn btn-info" value="">Balance</button></a>
        <a href="{% url 'cards:withdrawal' %}"><button class="btn btn-info" value="">Cash</button></a>
    </div>

{% endblock %}

{% block script %}
{% endblock %}

cards/templates/cards/card-password.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{block.super}} - Input Card Number{% endblock %}

{% block content %}

    <div class="row input-field">
        <h3>Input card PASSWORD:</h3>
        <div ><input disabled id="card-pass-input" class="align-center" type="text" /></div>
        <br/>
    </div>

    <div class="row control-row">
        <a href="{% url 'logout' %}"><button class="btn btn-info" value="">Exit</button></a>
        <button disabled class="btn" value="">Balance</button>
        <button disabled class="btn" value="">Cash</button>
    </div>

    {% include 'keyboard.html' with action='/card/pass/'%}
{% endblock %}

{% block script %}
    <script src="{% static 'js/md5.min.js' %}"></script>
    <script src="{% static 'js/card_pass_validator.js' %}"></script>
{% endblock %}

cards/templates/cards/card-withdrawal.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{block.super}} - Card Withdrawal{% endblock %}

{% block content %}

    <div class="row input-field">
        <h3>Input cash amount:</h3>
        <div ><input disabled id="card-cash-input" class="align-center" type="text" /></div>
        <br/>
    </div>

    <div class="row control-row">
        <a href="{% url 'logout' %}"><button class="btn btn-info" value="">Exit</button></a>
        <button disabled class="btn" value="">Balance</button>
        <button disabled class="btn" value="">Cash</button>
    </div>
    {% include 'keyboard.html' with action='/card/withdrawal/' %}
{% endblock %}

{% block script %}
    <script src="{% static 'js/card_cash_validator.js' %}"></script>
{% endblock %}